[package]
authors = ["James O'Brien"]
description = "A library for rendering vector shapes using the Bevy game engine"
edition = "2021"
exclude = [
  "assets/*",
]
homepage = "https://github.com/james-j-obrien/bevy_vector_shapes"
keywords = ["bevy", "gamedev", "graphics"]
license = "MIT OR Apache-2.0"
name = "bevy_vector_shapes"
repository = "https://github.com/james-j-obrien/bevy_vector_shapes"
version = "0.7.0"

[dependencies]
any_vec = "0.13.0"
bevy = { version = "0.13" , default-features = false, features = [
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_render",
  "bevy_sprite",
  "bevy_winit",
  "hdr",
  "ktx2",
  "tonemapping_luts",
  "x11",
  "zstd",
]}
bitfield = "0.14.0"
bitflags = "2.3"
smallvec = "1.13.1"
wgpu = { version = "0.19.3", default-features = false }
